{ lib, pkgs, ... }:
  let
    inherit (lib) makeBinPath;

  in {
    # Rage CLI for encrypting secrets.
    environment.systemPackages = with pkgs; [
      rage
      age-plugin-yubikey
    ];

    # Hack to put `age-plugin-yubikey` in PATH so that
    # `rage` can find it while rebuilding the system.
    age.ageBin = "PATH=${makeBinPath [pkgs.age-plugin-yubikey]} ${pkgs.rage}/bin/rage";

    # Instruct age to use the identity file for the YubiKey
    # which was generated by `age-plugin-yubikey`. Otherwise
    # it won't find the keys needed to decrypt any secrets.
    age.identityPaths = [
      ./identities/yubikey-identity.txt
    ];

    age.secrets.sext_ovpn_config.file = ./sext_config.ovpn.age;
  }
