{ config, lib, pkgs, isWSL, ... }:
  let
    inherit (lib) makeBinPath;

    yubikey = "age1yubikey1qvm8ruv0vy6e8893q3vx9730yz95uqyxdyaucennynjq0rx44rmhkrexvne";
    yubikeyIdentity = ./identities/yubikey-identity.pub;

  in if (!isWSL) then {
    # Rage CLI for encrypting secrets.
    environment.systemPackages = with pkgs; [
      rage
      age-plugin-yubikey
    ];

    # Make `agenix` use the `rage` CLI by default.
    age.ageBin = "PATH=${makeBinPath [pkgs.age-plugin-yubikey]}:$PATH ${pkgs.rage}/bin/rage";

    # Instruct age to use the identity file for the YubiKey
    # which was generated by `age-plugin-yubikey` and also
    # set it as the master identity for rekeying.
    age.identityPaths = [yubikeyIdentity];
    age.rekey.hostPubkey = yubikey;
    age.rekey.masterIdentities = [yubikeyIdentity];

    age.secrets."3ds_aes_keys".file = ./3ds-aes-keys.age;
    age.secrets.sext_ovpn.file = ./sext.ovpn.age;
    age.secrets.sext_creds.file = ./sext-creds.auth.age;
    age.secrets.vale_password.file = ./vale-password.age;
  } else {
    # WSL does not support USB passthrough in a way that doesn't suck.
    # Using a public key identity exclusively for the user there.

    age.identityPaths = ["/home/vale/.ssh/id_ed25519"];

    age.secrets."3ds_aes_keys".file = ./3ds-aes-keys.age;
    age.secrets.vale_password.file = ./vale-password.age;
  }
